### ISSUE TITLE
Failing `npm run build` during server page prerender at `useTranslation`

### ISSUE THREAD

**Issue by macoley** [aralroca/next-translate-plugin#15]

**Comment by macoley** [comment]
@aralroca I keep `app` and `pages` together, because I use tRPC under `pages/api/[trpc].tsx` and that approach is way simpler.

**Comment by aralroca** [comment]
Can you try changing the name of `pages` to another one for a moment, only to verify that is for this?

**Comment by picardplaisimond** [comment]
> Can you try changing the name of `pages` to another one for a moment, only to verify that is for this?

I just tried that solution, and it seems to work for me. It would have been great if both folder could cohabit.

- However, it's clear that the new App directory structure is not stable yet. I wanted to give it a chance, but it's way too soon to migrate.
- I'm wondering if there's a easier way to make this package works with the App directory structure. Right now, it seems like there's a lot of workarounds happening in the background, making this package more fragile.

**Comment by bbolek** [comment]
I am having the same issue
![image](https://github.com/aralroca/next-translate-plugin/assets/1146456/b59c0914-119a-4567-a407-48c2de0f8d76)

I dont have pages folder. I just removed it. But still failing..

**Comment by aralroca** [comment]
Try next-translate-plugin prerelease [2.3.0-canary.1](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.1)

**Comment by bbolek** [comment]
Now I am having totally different error:
![image](https://github.com/aralroca/next-translate-plugin/assets/1146456/2402ddc9-42d1-497c-8276-c7327a940a8f)

Thanks

**Comment by bbolek** [comment]
Hey @aralroca  I got this again:
![image](https://github.com/aralroca/next-translate-plugin/assets/1146456/85816663-b593-444c-95ec-4a0858ce2141)

Thank you.

**Comment by bbolek** [comment]
Small update: If I use Server action in related page, I can get build without any problem on version "next-translate-plugin": "^2.0.3",

But if there is no server action in related page, I get exception

**Comment by aralroca** [comment]
Thanks for the comment, is possible to upload the reproducible failing case in some repo to help to fix It? Thanks!

**Comment by bbolek** [comment]
Hey @aralroca, I shared a repo with you : https://github.com/bbolek/next-translate-issue

Thank you

**Comment by aralroca** [comment]
@bbolek looks fixed in:

- `next-translate` version `2.3.0-canary.3`
- `next-translate-plugin` version `2.3.0-canary.3`

**Comment by bbolek** [comment]
@aralroca Still having the issue. updated package.json and pushed to repo

Thanks
